### ISSUE TITLE
Execution of Tests

### ISSUE THREAD

**Issue by tbergen1** [mohaldev/gatherTesting#1]
After getting your project set up on my machine, I wasn't able to successfully run the tests.  I kept running into some sort of permissions issue.  Did you change some sort of dependency in the project because I have never seen this on anybody else's submitted project?

**Comment by mohaldev** [comment]
@tbergen1  Thanks, Ted. For some reason, I ran into issues when I downloaded the based code. npm install gave me a bunch of issues to use "x" package over "y".  That meant I had to install ceratin packages individually. 

Any reason, you might think of?
