### ISSUE TITLE
Summary - Meets Expectations

### ISSUE THREAD

**Issue by tbergen1** [mohaldev/gatherTesting#4]
Overall, you did a great job. I couldn't run your tests due to some permissions issue with your repo, but your code looked accurate after reviewing it. Your code base was structured well and your formatting made reading and reviewing the code very easy. You could improve your code moving forward by adding comments detailing what logical groupings of code are doing, but other than that it is some really great work! Keep it up!

**Comment by mohaldev** [comment]
Super! Thanks for the review. I have replied to your comment about the permissions etc. in the other thread. 

Have a great holiday season ahead :)
